### ISSUE TITLE
Follow PEP 8 standard for Python source code

### ISSUE THREAD

**Issue by freakeinstein** [Aquila-Network/aquila#21]

**Comment by niazangels** [comment]
Hey, have you considered [black](https://github.com/psf/black/)?
Some things that you can do to migrate is:

1. Have the autoformatter set in your editor that gets triggered on file save (I have done this with VS Code and boy, it saved a lot of manual effort for me)
2. Have a git pre commit hook that will invoke black whenever someone performs a git commit
3. Have a CI step that performs a black validation whenever there is a push. This will catch any commits where the author did not have a pre commit hook performed locally.

**Comment by niazangels** [comment]
I can pitch in if you need help with this. It'll probably also help me get familiar with the code base :slightly_smiling_face:

**Comment by freakeinstein** [comment]
We're thinking about refactoring most of the code base because the project has evolved beyond our initial concepts. We're open to any kind of contributions. In fact, we're running short in time and resource. We are planning to start refactoring as a separate branch and we will let you know here or through any other contact medium you prefer. Meanwhile, you can go through current code base because the core concepts, libraries and APIs will remain the same. 

We appreciate your time and effort..

**Comment by freakeinstein** [comment]
We've started code refactoring. Firstly focusing on vector storage part (FAISS). All development goes to this branch https://github.com/a-mma/AquilaDB/tree/refactor
